---
  version: '3.3'

  services:
    nldi:
      image: internetofwater/nldi-py:latest
      container_name: nldi
      build:
        context: .
        args:
          DOCKER_MIRROR: ${DOCKER_MIRROR}
      ports:
        - 9999:80
      environment:
        NLDI_PATH: /nldi
        NLDI_URL: http://localhost:9999/nldi
        NLDI_DB_HOST: nldi-db
        NLDI_DB_PORT: 5432
        NLDI_DB_USERNAME: read_only_user
        NLDI_DB_PASSWORD: changeMe
        NLDI_DB_NAME: nldi
        PYGEOAPI_URL: "https://labs.waterdata.usgs.gov/api/nldi/pygeoapi/"
      networks:
        - nldi
    nldi-db:
      image: ghcr.io/internetofwater/nldi-db:demo
      container_name: nldi-db-demo
      environment:
        POSTGRES_PASSWORD: changeMe
        NLDI_DATABASE_ADDRESS: localhost
        NLDI_DATABASE_NAME: nldi
        NLDI_DB_OWNER_USERNAME: nldi
        NLDI_DB_OWNER_PASSWORD: changeMe
        NLDI_SCHEMA_OWNER_USERNAME: nldi_schema_owner
        NLDI_SCHEMA_OWNER_PASSWORD: changeMe
        NHDPLUS_SCHEMA_OWNER_USERNAME: nhdplus
        NLDI_READ_ONLY_USERNAME: read_only_user
        NLDI_READ_ONLY_PASSWORD: changeMe
      networks:
        - nldi

  networks:
    nldi:
